FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
ENV NODE_ENV=development
RUN npm install && npm cache clean --force

# Copy source code
COPY . .

# Expose the port Vite runs on
EXPOSE 5173

# Start the development server with hot reloading and host set to allow connections from outside
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 