name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Docker and configure sudo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Check if Docker is installed
          if ! command -v docker &> /dev/null; then
            # Install Docker
            curl -fsSL https://get.docker.com -o get-docker.sh
            chmod +x get-docker.sh
            bash get-docker.sh
          fi

          # Check if Docker Compose is installed
          if ! command -v docker-compose &> /dev/null; then
            # Install Docker Compose
            sudo apt update
            sudo apt install -y docker-compose
          fi

          # Add user to docker group if not already
          if ! groups | grep -q docker; then
            sudo usermod -aG docker $USER
            echo "Added user to docker group. This will take effect after next login."
          fi
          
          # Configure passwordless sudo for docker and docker-compose
          echo "Configuring passwordless sudo for docker commands..."
          sudo tee /etc/sudoers.d/docker-commands > /dev/null << EOL
          $USER ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/bin/docker-compose
          EOL
          sudo chmod 440 /etc/sudoers.d/docker-commands
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p ~/sanad
          cd ~/sanad
          
          # Clone or update repository
          if [ -d ".git" ]; then
            git fetch origin main
            git reset --hard origin/main
          else
            git init
            git remote add origin https://github.com/aselims/sanad.git
            git fetch origin main
            git reset --hard origin/main
          fi
          
          # Create .env file with secrets
          cat > .env << EOL
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=sanad
          EOL
          
          # Run docker commands with sudo (doesn't require password now)
          sudo docker-compose build
          sudo docker-compose up -d 