name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p /opt/sanad
          cd /opt/sanad
          
          # Clone or update repository
          if [ -d ".git" ]; then
            git fetch origin main
            git reset --hard origin/main
          else
            git init
            git remote add origin https://github.com/aselims/sanad.git
            git fetch origin main
            git reset --hard origin/main
          fi
          
          # Create .env file with secrets
          cat > .env << EOL
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=sanad
          EOL
          
          # Build and run with Docker
          docker-compose build
          docker-compose up -d 